# On utilise une version de Node compatible avec Vite 6
FROM node:22-alpine

WORKDIR /app

# On installe les dépendances d'abord (optimisation du cache)
COPY package*.json ./
RUN npm install

# On copie le reste du code
COPY . .

# Vite utilise le port 5173 par défaut
EXPOSE 5173

# Commande pour lancer le mode dev
# --host est obligatoire pour que Docker laisse passer le trafic vers ton navigateur
CMD ["npm", "run", "dev", "--", "--host"]